sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
services:
  - mongodb
node_js:
  - "12"
before_script:
  - sudo npm install -g node-red
  - sudo npm link node-red
  - sudo npm install -g mocha
  - sudo npm install -g semistandard
  - sudo npm install -g snazzy
